from typing import Protocol
from app.schemas.incident import Incident
class IncidentRepository(Protocol):
    def get(self, incident_id: str) -> Incident: ...
    def put(self, incident: Incident) -> None: ...
    def ordered(self) -> list[Incident]: ...
# Future persistence must provide atomic ACK + idempotency + audit + outbox transactions.
